name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  DOCKERFILE_MTB_PATH: './mountain_bike_api'
  DOCKER_IMAGE_NAME: 'mountainbikeapi'
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
     - uses: azure/docker-login@v1
       with:
          login-server: ${{secrets.ACR_SERVER}}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
     - name: 'Build Dockerfile'
       shell: pwsh
       run: |
        ls
        pushd '${{env.DOCKERFILE_MTB_PATH}}'
        docker build . --tag my-image-name:latest
        
     - name: 'Push Dockerfile'
       shell: pwsh
       run: |
        pushd '${{env.DOCKERFILE_MTB_PATH}}'
        docker push -a ${{secrets.ACR_SERVER}}/${{env.DOCKER_IMAGE_NAME}}
        
